name: 'Deploy Cloud Run Service with CI/CD'

on:
  push:
    branches:
    - "stg"
    - "dev"

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_PROJECT_NUMBER: ${{ vars.GCP_PROJECT_NUMBER }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  INPUT_DATASET: ${{ vars.INPUT_DATASET }}
  OUTPUT_DATASET: ${{ vars.OUTPUT_DATASET }}
  SERVICE_ACCOUNT_RUNTIME: ${{ vars.SERVICE_ACCOUNT_RUNTIME }}
  SERVICE_ACCOUNT_GH: ${{ vars.SERVICE_ACCOUNT_GH }}
  WIF_POOL_ID: ${{ vars.WIF_POOL_ID }} # Workload Identity Federation Pool
  WIF_POOL_PROVIDER: ${{ vars.WIF_POOL_PROVIDER }} # Workload Identity Federation Provider
  PROJECT: ${{ vars.PROJECT }} # Cloud Run service name (same as repo name)
  UV_VERSION: 0.11.6 # Version of uv to install

jobs:

  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v6

    - name: Authentication to Google Cloud Platform
      uses: google-github-actions/auth@v3
      with:
        token_format: access_token
        workload_identity_provider: 'projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL_ID }}/providers/${{ env.WIF_POOL_PROVIDER }}'
        service_account: ${{ env.SERVICE_ACCOUNT_GH }}
        access_token_lifetime: 300s

    - name: Install uv
      uses: astral-sh/setup-uv@v8.0.0
      with:
        version: ${{ env.UV_VERSION }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build and Push to Artifact Registry
      run: |
        IMAGE=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/cloud-run/app:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy Cloud Run Service (auth required and internal ingress)
      run: |
        IMAGE=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/cloud-run/app:${{ github.sha }}
        gcloud run deploy ${{ env.PROJECT }} \
          --image=$IMAGE \
          --region=${{ env.GCP_REGION }} \
          --platform=managed \
          --memory=1Gi \
          --no-allow-unauthenticated \
          --ingress=internal-and-cloud-load-balancing \
          --service-account=${{ env.SERVICE_ACCOUNT_RUNTIME }} \
          --set-env-vars GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }} \
          --set-env-vars INPUT_DATASET=${{ env.INPUT_DATASET }} \
          --set-env-vars OUTPUT_DATASET=${{ env.OUTPUT_DATASET }} \
          --set-secrets API_KEY=API_KEY:latest
